package com.icc.common.message;
/**
 * 
 * @description
 * @author zhurun
 * @date 2016年11月1日上午10:55:13
 */
public class CHECKMSG {

	public static final String VALIDATE_BATCHSIGN_USBKEYSN_NOTNULL="Validate.BatchSign.UsbKeySN.NotNull"; //第{0}行:USBKey编号不能为空
    public static final String VALIDATE_PLS_SELECT_TREE_PRODUCT="Validate.pls.select.tree.product"; //没有选择产品
    public static final String VALIDATION_RECORD_NOTEXISTS="Validation.Record.NotExists"; //记录不存在
    public static final String ENCRYPT_ERROR="encrypt.error"; //加密机加密异常
    public static final String IBS_PIN_ERROR="ibs.pin_error"; //密码加密异常,请重试
    public static final String PAGE_ERROR_INPUT_MESSAGE="page.error.input.message"; //请输入数字。
    public static final String PAGE_ERROR_SCOPE_BIGGER_MESSAGE="page.error.scope.bigger.message"; //输入页数不可大于当前总页数
    public static final String PAGE_ERROR_SCOPE_SAMLLER_MESSAGE="page.error.scope.samller.message"; //输入页数不能小于1
    public static final String SYSTEM_UNDEFINED_TRANSACTION="system.undefined_transaction"; //系统内部错误，交易未定义
    public static final String UIBS_AUTHENTICATE_ERROR="uibs.authenticate_error"; //操作员号或密码错误！
    public static final String UIBS_AUTHENTICATE_EXCEPTION="uibs.authenticate_exception"; //用户账号或密码不正确
    public static final String VALIATATION_BANKSUBACTYPE_ERROR="valiatation.BankSubAcType.Error"; //第{0}行:储种有误
    public static final String VALIATATION_CURRENCYCODE_ERROR="valiatation.CurrencyCode.Error"; //第{0}行:币种有误
    public static final String VALIATATION_INTEREST_ERROR="valiatation.Interest.Error"; //第{0}行：年利率格式错误，请重新编辑模板！
    public static final String VALIATATION_INTEREST_MAXERROR="valiatation.Interest.MaxError"; //第{0}行:利率值过大
    public static final String VALIATATION_INTERESTCD_ERROR="valiatation.InterestCd.Error"; //第{0}行：利率代码或描述不符，请重新编辑模板！
    public static final String VALIATATION_INTERESTCD_EXITED="valiatation.InterestCd.Exited"; //第{0}行和第{1}行的(利率代码)有重复
    public static final String VALIATATION_PRODUCT_ERROR="valiatation.Product.Error"; //第{0}行:存贷类型有误
    public static final String VALIATATION_DIVUSER_IS_EXIST="valiatation.divuser.is.exist"; //该部门有操作员在作用,不允许删除部门
    public static final String VALIATATION_ROLE_IS_EXITED="valiatation.role.is.exited"; //角色{0}已经存在！
    public static final String VALIATATION_SEQUENCE_ERROR="valiatation.sequence.error"; //第{0}行：序号格式错误，请重新编辑模板！
    public static final String VALIDATE_CCTRANSPWD_ALREADY_SET="validate.cctranspwd.already.set"; //不可重复设置信用卡密码
    public static final String VALIDATION_ACNO_REDUPLICATE="validation.AcNo.reduplicate"; //存在重复的账号
    public static final String VALIDATION_BINNO_REDUPLICATE="validation.BinNo.reduplicate"; //存在重复的BIN号
    public static final String VALIDATION_BUYPRICE_ERROR="validation.BuyPrice.Error"; //第{0}行:买入价有误
    public static final String VALIDATION_CIF_EIBS_EXIT="validation.CIF.EIBS.exit"; //该客户的网银渠道已开通
    public static final String VALIDATION_CIF_MCHANNEL_EXIT="validation.CIF.MChannel.exit"; //该客户已开通｛0｝
    public static final String VALIDATION_CIF_MCHANNELPMBS_NOTEXIT="validation.CIF.MChannelPMBS.notexit"; //该客户未开通手机银行
    public static final String VALIDATION_CASHBUYPRICE_ERROR="validation.CashbuyPrice.Error"; //第{0}行:现钞买入价有误
    public static final String VALIDATION_CLOSEPRICE_ERROR="validation.ClosePrice.Error"; //第{0}行:收盘价有误
    public static final String VALIDATION_CONTRACTCD_ERROR="validation.ContractCd.Error"; //第{0}行:合约有误
    public static final String VALIDATION_CONTRACTCD_EXITED="validation.ContractCd.Exited"; //第{0}行和第{1}行的(合约)有重复
    public static final String VALIDATION_CURRENCY_ERROR="validation.Currency.Error"; //第{0}行:币种有误
    public static final String VALIDATION_CURRENCY_EXITED="validation.Currency.exited"; //第{0}行和第{1}行的(币种)有重复
    public static final String VALIDATION_CURRENCYNAME_ERROR="validation.CurrencyName.Error"; //第{0}行:币种名有误
    public static final String VALIDATION_CURRENCYORNAME_EXITED="validation.CurrencyOrName.exited"; //第{0}行和第{1}行的(币种和币种名)有重复
    public static final String VALIDATION_FUNDCODE_EXITED="validation.FundCode.Exited"; //第{0}行和第{1}行的(基金代码)有重复
    public static final String VALIDATION_FUNDCODEORDATE_EXITED="validation.FundCodeOrDate.Exited"; //第{0}行和第{1}行的(基金代码和日期)有重复
    public static final String VALIDATION_MASTERACFLAG_NUMBER_ERR="validation.MasterAcFlag.Number.err"; //企业主账号不能超过1个
    public static final String VALIDATION_MIDPRICE_ERROR="validation.MidPrice.Error"; //第{0}行:中间价有误
    public static final String VALIDATION_PRODCODE_ERROR="validation.ProdCode.Error"; //第{0}行:产品代码有误
    public static final String VALIDATION_PRODCODE_EXIST="validation.ProdCode.Exist"; //第{0}行和第{1}行的(产品代码 )有重复
    public static final String VALIDATION_PRODCODEORYIELDDATE_EXIST="validation.ProdCodeOrYieldDate.Exist"; //第{0}行和第{1}行的(产品代码和收益率对应日期 )有重复
    public static final String VALIDATION_SELLPRICE_ERROR="validation.SellPrice.Error"; //第{0}行:卖出价有误
    public static final String VALIDATION_TEMPLATEEXPORT_DATE_ERROR="validation.TemplateExport.Date.Error"; //第{0}行：生效日期或生效时间格式错误，请重新编辑模板！
    public static final String VALIDATION_TEMPLATEEXPORT_EXCEL_NOTNULL="validation.TemplateExport.Excel.NotNull"; //导入的Excel不能为空或不是标准的模板
    public static final String VALIDATION_TEMPLATEEXPORT_FUNDCODE_ERROR="validation.TemplateExport.FundCode.Error"; //第{0}行:基金代码有误
    public static final String VALIDATION_UNIT_ERROR="validation.Unit.Error"; //第{0}行:单位有误
    public static final String VALIDATION_UNITVALUE_ERROR="validation.UnitValue.Error"; //第{0}行:基金单位净值(元)有误
    public static final String VALIDATION_USBKEYPASSWORD_MISMATCH="validation.UsbKeyPassword.mismatch"; //USBKey密码和确认密码不匹配
    public static final String VALIDATION_USBKEYSN_MISMATCH="validation.UsbKeySN.mismatch"; //USBKey编号和确认编号不匹配
    public static final String VALIDATION_USERID_REDUPLICATE="validation.UserId.reduplicate"; //存在重复的用户名
    public static final String VALIDATION_YIELDDATE_ERROR="validation.YieldDate.Error"; //第{0}行:收益率对应日期有误
    public static final String VALIDATION_YIELDRATE_ERROR="validation.YieldRate.Error"; //第{0}行:每日年化收益率有误
    public static final String VALIDATION_YIELDRATE_MAXERROR="validation.YieldRate.MaxError"; //第{0}行:每日年化收益率值过大
    public static final String VALIDATION_ACTYPE_DAYLIMIT_LARGE="validation.actype.daylimit.large"; //账号类型[{0}]日累计限额超过客户日累计限额。
    public static final String VALIDATION_ACTYPE_TRSLIMIT_LARGE="validation.actype.trslimit.large"; //账号类型[{0}]单笔限额超过日累计限额。
    public static final String VALIDATION_ADMIN_EMAIL_REQUIRED="validation.admin.email.required"; //操作员{0}为管理员,E-mail不能为空。
    public static final String VALIDATION_ADMINUSER_REQUIRED="validation.adminuser.required"; //至少需要申请{0}名{1}
    public static final String VALIDATION_CERT_FEE_FAIL="validation.cert.fee.fail"; //证书收费异常
    public static final String VALIDATION_CHECK_BATCHSIGN_COUNT="validation.check.batchsign.count"; //批量文件中的记录条数最小10条，最大200条。
    public static final String VALIDATION_CHECK_BATCHSIGN_QUERY="validation.check.batchsign.query"; //请输入核心客户号或组织机构号查询
    public static final String VALIDATION_CHECK_CERT_APPLY="validation.check.cert.apply"; //该证书状态无法进行证书申请操作
    public static final String VALIDATION_CHECK_CERT_CHANGE="validation.check.cert.change"; //该证书状态无法进行证书转换操作
    public static final String VALIDATION_CHECK_CERT_DOWNLOAD="validation.check.cert.download"; //当前状态不能进行下载操作
    public static final String VALIDATION_CHECK_CERT_FEE="validation.check.cert.fee"; //当前收费状态不能进行该操作。
    public static final String VALIDATION_CHECK_CERT_QUERY="validation.check.cert.query"; //请输入证件号码或卡折号进行查询
    public static final String VALIDATION_CHECK_CERT_RENEW="validation.check.cert.renew"; //当前证书状态不能进行恢复操作
    public static final String VALIDATION_CHECK_CERT_UPDATE="validation.check.cert.update"; //当前证书状态不能进行更新操作
    public static final String VALIDATION_CHECK_COMMISSIONCODE_ERR="validation.check.commissioncode.err"; //{0}错误，佣金代码找不到相应的贷方账号。
    public static final String VALIDATION_CHECK_PER_USBKEY_UPDATE="validation.check.per.usbkey.update"; //文件证书无法进行USBkey更换
    public static final String VALIDATION_CHECK_QUERY_CONDITION="validation.check.query.condition"; //请输入检索条件进行查询
    public static final String VALIDATION_CHECK_USBKEY_SAME="validation.check.usbkey.same"; //新老USBKey编号不能相同。
    public static final String VALIDATION_CHECK_USBKEY_SN_MODIFY="validation.check.usbkey.sn.modify"; //当前证书状态不能进行USBKey编号修改操作
    public static final String VALIDATION_CHECK_USBKEY_UPDATE="validation.check.usbkey.update"; //当前证书状态无法进行USBkey更换
    public static final String VALIDATION_CLOSEDATE_LESS_CURRENT="validation.closedate.less.current"; //关闭日期时间不能小于当前时间
    public static final String VALIDATION_CORE_USER_NOEXIT="validation.core.user.noexit"; //核心系统中无符合条件的用户
    public static final String VALIDATION_TYPE_DATE="validation.type.date"; //日期不正确
    public static final String VALIDATION_DATE="validation.date"; //输入的日期不正确
    public static final String VALIDATION_DATE_COMPARE="validation.date.compare"; //结束日期不能小于开始日期
    public static final String VALIDATION_DATE_CURRENT="validation.date.current"; //日期不能大于当前时间
    public static final String VALIDATION_DATE_LESS="validation.date.less"; //失效日期不能小于生效日期
    public static final String VALIDATION_DATE_LESS_CURRENT="validation.date.less.current"; //生效日期不能小于当前时间
    public static final String VALIDATION_DEPT_MISMATCH="validation.dept.mismatch"; //柜员机构不匹配
    public static final String VALIDATION_DIGIT="validation.digit"; //{0}必须为数字
    public static final String VALIDATION_ENDDATE_MORE_DATE="validation.enddate.more.date"; //结束日期不能大于当日
    public static final String VALIDATION_EXCEED_LONG_DATE="validation.exceed.long.date"; //只允许查询{0}内的记录
    public static final String VALIDATION_EXCEED_RANGE_DATE="validation.exceed.range.date"; //查询日期范围太大，最大可查{0}的记录
    public static final String VALIDATION_FEECODE_DEL_ERR="validation.feecode.del.err"; //该费用有关联交易，请先把费用从关联交易中删除。
    public static final String VALIDATION_IDENTITYNO_NOMATCH="validation.identityno.nomatch"; //系统中无客户的该证件信息
    public static final String VALIDATION_INVALID_USERSTATE="validation.invalid.userstate"; //操作员状态不正常!
    public static final String VALIDATION_INVALID_UPLOAD_FILE="validation.invalid_upload_file"; //上传文件无效
    public static final String VALIDATION_LENGTH="validation.length"; //{0}长度不匹配
    public static final String VALIDATION_LISTACNAME_REQUIRED="validation.listAcName.required"; //户名不能为空
    public static final String VALIDATION_LISTACNO_PATTERN="validation.listAcNo.pattern"; //账号不符合要求格式
    public static final String VALIDATION_LISTACNO_REQUIRED="validation.listAcNo.required"; //账号不能为空
    public static final String VALIDATION_LOGINID_PATTERN_ERR="validation.loginId.pattern.err"; //网上银行用户名不符合要求格式。
    public static final String VALIDATION_LOGIN_FAILED="validation.login_failed"; //用户名或密码无效
    public static final String VALIDATION_MASTERACNO_MUSTNOT_EMPTY="validation.masteracno.mustnot.empty"; //请指定主账户
    public static final String VALIDATION_MUST_COMPLICATED_PASSWORD="validation.must.complicated.password"; //密码必须为数字、字母和可见字符两两组合而成
    public static final String VALIDATION_MUST_SIMPLE_PASSWORD="validation.must.simple.password"; //密码必须非空白字符
    public static final String VALIDATION_OPENDATE_LESS_CURRENT="validation.opendate.less.current"; //重开日期时间不能小于当前时间
    public static final String VALIDATION_ORGCODE_PATTERN="validation.orgcode.pattern"; //组织机构代码不符合要求格式
    public static final String VALIDATION_ORGCODE_REQUIRED="validation.orgcode.required"; //组织机构代码不能为空
    public static final String VALIDATION_PASSWORD_LENGTH_NOCHAR="validation.password.length.nochar"; //密码必须至少包含一位字母
    public static final String VALIDATION_PASSWORD_LENGTH_NUMBERCHAR="validation.password.length.numberchar"; //密码只能包含数字和英文字符
    public static final String VALIDATION_PASSWORD_LENGTH_ONLYNUMBER="validation.password.length.onlynumber"; //密码只能包含数字
    public static final String VALIDATION_PASSWORD_LENGTH_TOOLONG="validation.password.length.toolong"; //密码长度不能大于{0}位
    public static final String VALIDATION_PASSWORD_LENGTH_TOOSHORT="validation.password.length.tooshort"; //密码长度不能小于{0}位
    public static final String VALIDATION_PASSWORD_MISMATCH="validation.password.mismatch"; //新密码和确认密码不一致
    public static final String VALIDATION_PATTERN="validation.pattern"; //{0}不符合要求格式
    public static final String VALIDATION_PLS_SET_RULE="validation.pls.set.rule"; //请设置规则{0}值
    public static final String VALIDATION_REQUIRED="validation.required"; //{0}不能为空
    public static final String VALIDATION_REQUIRED_FIELD="validation.required.field"; //至少需要申请{0}个{1}
    public static final String VALIDATION_SAMPLE_PWD="validation.sample.pwd"; //不允许为简单密码
    public static final String VALIDATION_SETTING_ISNOCHECK="validation.setting.isnocheck"; //请至少选择一个产品
    public static final String VALIDATION_SIGN_CHANGE_STATEERROR="validation.sign.change.stateerror"; //渠道状态非正常，不可进行注销或者变更。
    public static final String VALIDATION_SIGN_MASTERAC_ERROR="validation.sign.masterac.error"; //主账号必须是活期人民币账号。
    public static final String VALIDATION_SIGN_USER_IDNO_REDUPLICATE="validation.sign.user.idno.reduplicate"; //操作员{0}和{1}证件重复。
    public static final String VALIDATION_SIGNATURE_VERIFY_ERROR="validation.signature.verify.error"; //非法数字签名
    public static final String VALIDATION_SUBSYSTALK_ERROR="validation.subsystalk.error"; //单点登录通信私钥异常{0}
    public static final String VALIDATION_TELLER_MCHSATE_CLOSE="validation.teller.mchsate.close"; //该操作员已注销
    public static final String VALIDATION_TELLER_NOEXIT="validation.teller.noexit"; //操作员{0}不存在
    public static final String VALIDATION_VERY_BIG_WORD="validation.very.big.word"; //您上传的文档过大
    public static final String VALIDATION_PHONEDEPTID_EXIST="Validation.phonedeptid.exist"; //存在重复的用户名
    public static final String VALIDATION_FOREXCH_ERROR="Validation.forexch.error"; //第{0}行第{1}个字段格式不正确
    public static final String VALIDATION_USERID_INUSE="validation.userid.inuse"; //理财产品编号已存在
    public static final String VALIDATION_CERT_IS_ERROR="validation.cert.is.error"; //公钥文件不正确，请更换后再试
    public static final String VALIDATION_SGHAC_ERROR="validation.sghac.is.error"; //垫资户不能为空(old)
    public static final String VALIDATION_DZHNULL_ERROR="validation.dzhnull.error";//垫资户不能为空
    public static final String VALIDATION_DZH_IS_ERROR="validation.dzh.is.error";//垫资户格式不正确
    public static final String VALIDATION_JSHNULL_ERROR="validation.jshnull.error";//结算不能为空
    public static final String VALIDATION_JSH_IS_ERROR="validation.jsh.is.error";//结算格式不正确
    public static final String VALIDATION_CARDTYPE_ISNULL_ERROR="validation.cardtype_isnull.error";//卡类型编号不能为空
    public static final String VALIDATION_CARDTYPE_STYLE_ERROR="validation.cardtype.style.error";//卡类型编号格式不正确
    public static final String VALIDATION_SGHNULL_ERROR="validation.sghnull.error";//申购户不能为空
    public static final String VALIDATION_SGH_IS_ERROR="validation.sgh.is.error";//申购户格式不正确
    public static final String VALIDATION_SXFACNULL_ERROR="validation.sxfacnull.is.error"; //手续费账号不能为空
    public static final String VALIDATION_SXFAC_ERROR="validation.sxfac.is.error"; //手续费账号格式不正确
    public static final String VALIDATION_SHHACNULL_ERROR="validation.shhacnull.is.error"; //赎回号不能为空
    public static final String VALIDATION_SHHAC_ERROR="validation.shhac.is.error"; //赎回号格式不正确
    public static final String VALIDATION_STARTDATE_ERROR="validation.saleQuotient.is.error"; //销售额度只能增不能减
    public static final String VALIDATION_ENDDATE_MORE_STARTDATE="validation.endDate.must.more.startDate";//产品到期日必须大于等于产品起息日期
    public static final String VALIDATION_ENDDATE_MORE_SALEDATE="validation.endDate.must.more.saleDate";//产品到期日必须大于产品销售起始日期
    public static final String VALIDATION_STARTDATE_LESS_CURRENT="validation.startdate.less.current";//产品起息日不能小于当前日
    public static final String VALIDATION_ENDDATE_LESS_CURRENT="validation.enddate.less.current";//产品到期日不能小于当前日
    public static final String VALIDATION_STARTDATE_MORE_SALEDATE="validation.startDate.must.more.saleDate";////产品起息日必须大于产品销售起始日期
    public static final String VALIDATION_ENDDATE_MORE_NOWDATE="validation.enddate.more.nowdate"; //结束日期不能大于当日
    
    public static final String VALIDATION_CURRENTUSERID_ISNULL_ERROR="validation.currentusernull.error";//当前用户ID不能为空
    public static final String VALIDATION_RENTUSERID_ISNULL_ERROR="validation.rentusernull.error";//租户ID不能为空
    public static final String VALIDATION_RENTTREM_IS_ERROR="validation.renttrem.error";//租赁周期{0}格式不正确
    public static final String VALIDATION_AREANOS_IS_ERROR="validation.areanos.error";//过滤条件区域{0}格式不正确
    public static final String VALIDATION_ESTATESTYPES_IS_ERROR="validation.estatestypes.error";//过滤条件物业类型{0}格式不正确
    public static final String VALIDATION_USERID_ISNULL_ERROR="validation.userid.isnull.error";//用户ID不能为空
    public static final String UPLOAD_SHOPSPHOTO_2OSS_FAIL="local.file.to.oss.fail";//本地文件{0}上传OSS失败
}
